language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - pipenv install --system --dev

script:
  - pipenv run py.test --cov=./stream

after_success:
  - codecov
